# Base image
FROM python:3.9.2

# Set working directory
WORKDIR /app

# Copy files
COPY main.py /app
COPY requirementsv2.txt /app
COPY model.h5 /app
COPY predict.py /app

# Install dependencies
RUN pip install -r requirements.txt

# Run the application
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]